# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d07a69e488994fff442531c3a770c516a7f64324e61b16aee4f42d338d8e3c2d4dbb936ae1a6c0804f99a1de0eeb9c25ec3b47c8349595248af5806df39809

test:
  secret_key_base: 6094ec697d9275c318627ccf6ae33569f1a68f21db300ee8fbdb4df8ef9978fb017952b3a26d31c4e29ac14cc016828d26ffd83284684d77b487d08dfa440453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
